controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 0.05
      panda_joint1:
        goal: 0.05
      panda_joint2:
        goal: 0.05
      panda_joint3:
        goal: 0.05
      panda_joint4:
        goal: 0.05
      panda_joint5:
        goal: 0.05
      panda_joint6:
        goal: 0.05
      panda_joint7:
        goal: 0.05

gripper_trajectory_controller:
  ros__parameters:
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
